global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'checkmate-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['checkmate-be:8081']

  - job_name: 'postgres'
    static_configs:
      - targets: ['db-server:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-server:9121']